### ISSUE TITLE
android.os.Parcel.readIntArray(Parcel.java:784) Exception

### ISSUE THREAD

**Issue by marcohc** [code-troopers/android-betterpickers#194]
I though this bug was fixed, but no...

Caused by: java.lang.NullPointerException
       at android.os.Parcel.readIntArray(Parcel.java:784)
       at com.codetroopers.betterpickers.numberpicker.NumberPicker$SavedState.()
       at com.codetroopers.betterpickers.numberpicker.NumberPicker$SavedState.()
       at com.codetroopers.betterpickers.numberpicker.NumberPicker$SavedState$1.createFromParcel()
       at android.os.Parcel.readParcelable(Parcel.java:2103)
       at android.os.Parcel.readValue(Parcel.java:1965)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
       at android.os.Parcel.readSparseArray(Parcel.java:1687)
       at android.os.Parcel.readValue(Parcel.java:2022)
       at android.os.Parcel.readMapInternal(Parcel.java:2226)
       at android.os.Bundle.unparcel(Bundle.java:223)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:1240)
       at android.support.v4.app.FragmentManagerImpl.moveToState()
       at android.support.v4.app.FragmentManagerImpl.moveToState()
       at android.support.v4.app.FragmentManagerImpl.moveToState()
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate()
       at android.support.v4.app.FragmentActivity.onCreate()
       at android.support.v7.app.AppCompatActivity.onCreate()
       at com.disegnator.financiator.presentation.ui.activity.AddRecordActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:5224)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2385)
       at android.app.ActivityThread.access$600(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by fchauveau** [comment]
Hi, 

Indeed this issue is fixed via recent PR #62
But released has not yet been done. 
It will be available next week

**Comment by marcohc** [comment]
Cooool, thanks :)
