### ISSUE TITLE
Error inflating DatePicker

### ISSUE THREAD

**Issue by alexodus** [code-troopers/android-betterpickers#214]
I have this from an acra crash report

```
12-01 22:15:29.986 E/ACRA    (23048): android.view.InflateException: Binary XML file line #7: Error inflating class com.codetroopers.betterpickers.datepicker.DatePicker
12-01 22:15:29.986 E/ACRA    (23048):   at android.view.LayoutInflater.createView(LayoutInflater.java:620)
12-01 22:15:29.986 E/ACRA    (23048):   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
12-01 22:15:29.986 E/ACRA    (23048):   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
12-01 22:15:29.986 E/ACRA    (23048):   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
12-01 22:15:29.986 E/ACRA    (23048):   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
12-01 22:15:29.986 E/ACRA    (23048):   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
12-01 22:15:29.986 E/ACRA    (23048):   at com.codetroopers.betterpickers.datepicker.DatePickerDialogFragment.onCreateView(DatePickerDialogFragment.java:119)
12-01 22:15:29.986 E/ACRA    (23048):   at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
12-01 22:15:29.986 E/ACRA    (23048):   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
12-01 22:15:29.986 E/ACRA    (23048):   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
12-01 22:15:29.986 E/ACRA    (23048):   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
12-01 22:15:29.986 E/ACRA    (23048):   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
12-01 22:15:29.986 E/ACRA    (23048):   at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
12-01 22:15:29.986 E/ACRA    (23048):   at android.os.Handler.handleCallback(Handler.java:808)
12-01 22:15:29.986 E/ACRA    (23048):   at android.os.Handler.dispatchMessage(Handler.java:103)
12-01 22:15:29.986 E/ACRA    (23048):   at android.os.Looper.loop(Looper.java:193)
12-01 22:15:29.986 E/ACRA    (23048):   at android.app.ActivityThread.main(ActivityThread.java:5299)
12-01 22:15:29.986 E/ACRA    (23048):   at java.lang.reflect.Method.invokeNative(Native Method)
12-01 22:15:29.986 E/ACRA    (23048):   at java.lang.reflect.Method.invoke(Method.java:515)
12-01 22:15:29.986 E/ACRA    (23048):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
12-01 22:15:29.986 E/ACRA    (23048):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
12-01 22:15:29.986 E/ACRA    (23048):   at dalvik.system.NativeStart.main(Native Method)
12-01 22:15:29.986 E/ACRA    (23048): Caused by: java.lang.reflect.InvocationTargetException
12-01 22:15:29.986 E/ACRA    (23048):   at java.lang.reflect.Constructor.constructNative(Native Method)
12-01 22:15:29.986 E/ACRA    (23048):   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12-01 22:15:29.986 E/ACRA    (23048):   at android.view.LayoutInflater.createView(LayoutInflater.java:594)
12-01 22:15:29.986 E/ACRA    (23048):   ... 21 more
12-01 22:15:29.986 E/ACRA    (23048): Caused by: java.lang.IllegalArgumentException: Bad pattern character 'E' in E, d MMM yyyy
12-01 22:15:29.986 E/ACRA    (23048):   at libcore.icu.ICU.getDateFormatOrder(ICU.java:165)
12-01 22:15:29.986 E/ACRA    (23048):   at android.text.format.DateFormat.getDateFormatOrder(DateFormat.java:384)
12-01 22:15:29.986 E/ACRA    (23048):   at com.codetroopers.betterpickers.datepicker.DatePicker.(DatePicker.java:95)
12-01 22:15:29.986 E/ACRA    (23048):   ... 24 more
```

version betterpickes = 2.2.1

**Comment by fchauveau** [comment]
Hi @alexodus 
On which phone / android version do you get this crash ?

**Comment by alexodus** [comment]
Wiko LENNY (4.4.2)

**Comment by fchauveau** [comment]
Seems to be an Android bug https://code.google.com/p/android/issues/detail?id=82144
But google is not very interested in fixing it

**Comment by alexodus** [comment]
Mhh.....is there any workaround?

**Comment by alexodus** [comment]
There are a lot of devices with this bug (and with LOLLIPOP). In this condition this component is useless.
Why don't test this condition "inside" the component? See here: https://android-review.googlesource.com/#/c/194665/1/tests/tests/text/src/android/text/format/cts/DateFormatTest.java

**Comment by fchauveau** [comment]
It's a solution, but for now I never reproduce this issue.
I'll try again only on Lollipop. Which timezone and initial date/time did you used when getting the errors ?

**Comment by alexodus** [comment]
I also never reproduce this issue, but I have an app in production and I have different crash report with this bug. The latest are today: NGM_500 (5.0.2) and H60_PLUS (4.4.4). In my next release before use this component I will test this issue.

**Comment by alexodus** [comment]
I know that WIKO, NGM and H60, etc... are not widespread, but a crash is not desirable. IMHO the best solution is detect this condition inside the component (with specific exception code) and with a specific code to test this issue (like the test code created on android git repository some month ago)

**Comment by hgoebl** [comment]
I have an ACRA report with a new Chinese Android 6 phone model:

```
PRODUCT = x6069_cubot_5365u
MANUFACTURER=CUBOT
MODEL=CUBOT MAX
ANDROID_VERSION = 6.0
12-11 15:54:37.244 E/ACRA    (27540): Caused by: java.lang.IllegalArgumentException: Bad pattern character 'E' in E, d MMM yyyy
12-11 15:54:37.244 E/ACRA    (27540):   at libcore.icu.ICU.getDateFormatOrder(ICU.java:314)
12-11 15:54:37.244 E/ACRA    (27540):   at android.text.format.DateFormat.getDateFormatOrder(DateFormat.java:456)
12-11 15:54:37.244 E/ACRA    (27540):   at com.codetroopers.betterpickers.datepicker.DatePicker.<init>(DatePicker.java:95)
12-11 15:54:37.244 E/ACRA    (27540):   ... 23 more
```

Is there a workaround?

**Comment by hgoebl** [comment]
I don't expect this problem to be solved, but for others, I have another phone model with this problem:

MANUFACTURER=LENOVO
MODEL=Tab2A7-10F
PRODUCT=Tab2A7-10F
ANDROID_VERSION = 5.0

**Comment by hgoebl** [comment]
The problem lies in the way betterpickers detect the order of date (mm / dd / yy, dd / mm / yy, ...) and there are quite a lot Android devices which crash on `DateFormat.getDateFormatOrder(context)`. It's not the fault of betterpickers, BTW.

I've got a workaround: detect the problem upfront ("probing") and not use betterpickers in case of expectable problems:

```java
    private boolean canUseBetterDatePicker(Context context) {
        try {
            DateFormat.getDateFormatOrder(context);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void editDateOfBirth() {
        FragmentActivity activity = getActivity();
        if (activity == null) {
            return;
        }
        if (canUseBetterDatePicker(activity)) {
            DatePickerBuilder dpb = new DatePickerBuilder()
                    .setFragmentManager(activity.getSupportFragmentManager())
                    .setTargetFragment(BioSettingsFragment.this)
                    .setStyleResId(R.style.BetterPickersDialogFragment)
                    .setYearOptional(false);
            dpb.show();
        } else {
            Calendar calendar = Calendar.getInstance();
            calendar.setTimeInMillis(10L * 365 * 24 * 3600 * 1000); // ~1.1.1980
            DatePickerDialog datePickerDialog = new DatePickerDialog(activity,
                    this,
                    calendar.get(Calendar.YEAR),
                    calendar.get(Calendar.MONTH),
                    calendar.get(Calendar.DAY_OF_MONTH));
            datePickerDialog.show();
        }
    }

    @Override
    public void onDialogDateSet(int reference, int year, int monthOfYear, int dayOfMonth) {
        updateDateOfBirth(year, monthOfYear, dayOfMonth);
    }

    @Override
    public void onDateSet(DatePicker view, int year, int month, int dayOfMonth) {
        updateDateOfBirth(year, month, dayOfMonth);
    }

    private void updateDateOfBirth(int year, int monthOfYear, int dayOfMonth) {
        Calendar cal = Calendar.getInstance();
        cal.set(year, monthOfYear, dayOfMonth, 0, 0);
        Date dayOfBirth = cal.getTime();
        // TODO save/set the new value
    }
```
