### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by glailton** [code-troopers/android-betterpickers#220]
12-15 14:11:31.499 27553-27553/grsoft.com.br.qualonmero E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: grsoft.com.br.qualonmero, PID: 27553
                                                                          java.lang.NumberFormatException: Invalid int: "25808852580"
                                                                              at java.lang.Integer.invalidInt(Integer.java:138)
                                                                              at java.lang.Integer.parse(Integer.java:413)
                                                                              at java.lang.Integer.parseInt(Integer.java:367)
                                                                              at java.lang.Integer.parseInt(Integer.java:334)
                                                                              at com.codetroopers.betterpickers.numberpicker.NumberPicker.getNumber(NumberPicker.java:501)
                                                                              at com.codetroopers.betterpickers.numberpicker.NumberPickerDialogFragment$2.onClick(NumberPickerDialogFragment.java:192)
                                                                              at android.view.View.performClick(View.java:4780)
                                                                              at android.view.View$PerformClick.run(View.java:19866)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

How can I treat to use do not put a number bigger the array Interger?

**Comment by fchauveau** [comment]
Hi @glailton 

We will look at this bug asap
Thx
