### ISSUE TITLE
CalendarDatePicker errors --- NoClassDefFoundError

### ISSUE THREAD

**Issue by peterb0yd** [code-troopers/android-betterpickers#265]
Error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/animation/Keyframe;
          at com.codetroopers.betterpickers.Utils.getPulseAnimator(Utils.java:126)
          at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.setCurrentView(CalendarDatePickerDialogFragment.java:386)
          at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.onCreateView(CalendarDatePickerDialogFragment.java:336)
          at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
          at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
          at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
          at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
          at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
          at android.app.Activity.performStart(Activity.java:6253)
          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
          at android.app.ActivityThread.-wrap11(ActivityThread.java)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
          at android.os.Handler.dispatchMessage(Handler.java:102)
          at android.os.Looper.loop(Looper.java:148)
          at android.app.ActivityThread.main(ActivityThread.java:5417)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nineoldandroids.animation.Keyframe" on path: DexPathList[[zip file "/data/app/com.boyd.tipshield-2/base.apk"],nativeLibraryDirectories=[/data/app/com.boyd.tipshield-2/lib/x86, /vendor/lib, /system/lib]]
             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
             at com.codetroopers.betterpickers.Utils.getPulseAnimator(Utils.java:126) 
             at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.setCurrentView(CalendarDatePickerDialogFragment.java:386) 
             at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.onCreateView(CalendarDatePickerDialogFragment.java:336) 
             at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738) 
             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602) 
             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
             at android.app.Activity.performStart(Activity.java:6253) 
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
             at android.os.Handler.dispatchMessage(Handler.java:102) 
             at android.os.Looper.loop(Looper.java:148) 
             at android.app.ActivityThread.main(ActivityThread.java:5417) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                        Suppressed: java.lang.ClassNotFoundException: com.nineoldandroids.animation.Keyframe
             at java.lang.Class.classForName(Native Method)
             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                ... 23 more
                                                                     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

I implemetented  "CalendarDatePickerDialogFragment.OnDateSetListener" and the required methods - along with the exact code in the repo sample.

This is the code that creates the dialog:

```
`
    DateTime now = DateTime.now();
    CalendarDatePickerDialogFragment cdp = new CalendarDatePickerDialogFragment()
            .setOnDateSetListener(this)
            .setFirstDayOfWeek(Calendar.SUNDAY)
            .setPreselectedDate(now.getYear(), now.getMonthOfYear() - 1, now.getDayOfMonth())
            .setThemeDark(true);
    cdp.show(getSupportFragmentManager(), FRAG_TAG_DATE_PICKER);
```

`

Any ideas?

**Comment by fchauveau** [comment]
Hi @peterb0yd 

which version of the lib do you use ?
The error append on all version of Android ?

**Comment by peterb0yd** [comment]
2.5.2, although I realized in the end I could do without the library. Using
it was overkill in my particular case. Thanks for following up though.

On Tuesday, March 22, 2016, Florian Chauveau notifications@github.com
wrote:

> Hi @peterb0yd https://github.com/peterb0yd
> 
> which version of the lib do you use ?
> The error append on all version of Android ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/code-troopers/android-betterpickers/issues/265#issuecomment-199704394

## 

Peter

**Comment by CTKnight** [comment]
same issue on API23(Marshmellow)

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/animation/Keyframe;
                                                                           at com.codetroopers.betterpickers.Utils.getPulseAnimator(Utils.java:126)
                                                                           at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.setCurrentView(CalendarDatePickerDialogFragment.java:371)
                                                                           at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.onCreateView(CalendarDatePickerDialogFragment.java:325)
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nineoldandroids.animation.Keyframe" on path: DexPathList[[zip file "/data/app/com.myqsc.mobile3.alpha-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myqsc.mobile3.alpha-2/lib/arm, /data/app/com.myqsc.mobile3.alpha-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at com.codetroopers.betterpickers.Utils.getPulseAnimator(Utils.java:126) 
                                                                           at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.setCurrentView(CalendarDatePickerDialogFragment.java:371) 
                                                                           at com.codetroopers.betterpickers.calendardatepicker.CalendarDatePickerDialogFragment.onCreateView(CalendarDatePickerDialogFragment.java:325) 
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290) 
                                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677) 
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536) 
                                                                           at android.os.Handler.handleCallback(Handler.java:739) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                        Suppressed: java.lang.ClassNotFoundException: com.nineoldandroids.animation.Keyframe
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                ... 17 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```
