### ISSUE TITLE
java.lang.IllegalStateException: Fragment already added: b{41a6cb78 #2 time_dialog}

### ISSUE THREAD

**Issue by dirkam** [code-troopers/android-betterpickers#285]
I get crashes like this from time to time, but it's rare. I can't reproduce it, but I believe it's related to the TimePicker.
Do you happen to have an idea what can be the reason for this and how could I avoid it?

```
java.lang.IllegalStateException: Fragment already added: b{41a6cb78 #2 time_dialog}
    at android.support.v4.app.n.a (FragmentManager.java:1323)
    at android.support.v4.app.e.a (BackStackRecord.java:940)
    at android.support.v4.app.n.a (FragmentManager.java:1722)
    at android.support.v4.app.n$3.run (FragmentManager.java:612)
    at android.support.v4.app.n.h (FragmentManager.java:1617)
    at android.support.v4.app.n$1.run (FragmentManager.java:517)
    at android.os.Handler.handleCallback (Handler.java:615)
    at android.os.Handler.dispatchMessage (Handler.java:92)
    at android.os.Looper.loop (Looper.java:137)
    at android.app.ActivityThread.main (ActivityThread.java:4856)
    at java.lang.reflect.Method.invokeNative (Native Method)
    at java.lang.reflect.Method.invoke (Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1007)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:774)
    at dalvik.system.NativeStart.main (Native Method)
```

I call it like this:

```
TimePickerBuilder tpb = new TimePickerBuilder().setFragmentManager(mFragmentManager);
                        if (tpb != null && mFragmentManager != null && mFragmentManager.findFragmentByTag(MainFragment.TAG) != null) {
                            tpb.setTargetFragment(mFragmentManager.findFragmentByTag(MainFragment.TAG));
                        }
                        tpb.addTimePickerDialogHandler(new TimePickerDialogFragment.TimePickerDialogHandler() {
                            @Override
                            public void onDialogTimeSet(int reference, int hourOfDay, int minute) {

                            }
                        });
                        tpb.show();
```

**Comment by devnied** [comment]
Same issue with NumberPicker with some devices

```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: c{43dbb938 #4 number_dialog}
       at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1323)
       at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:944)
       at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1722)
       at android.support.v4.app.FragmentManagerImpl$4.run(FragmentManager.java:612)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5426)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Code:

```
NumberPickerBuilder picker = new NumberPickerBuilder()
                .setFragmentManager(mFragment.getFragmentManager())
                .setPlusMinusVisibility(View.INVISIBLE)
                .setStyleResId(R.style.NumberPicker)
                .setReference(view.getId())
                .setStyleResId(R.style.BetterPickersDialogFragment)
                .setTargetFragment(mFragment);
        picker.show();
```

**Comment by dirkam** [comment]
Yep, it happens with every picker.

**Comment by dirkam** [comment]
I still get these crashes, unfortunately.
