### ISSUE TITLE
java.lang.NullPointerException [version 2.5.6]

### ISSUE THREAD

**Issue by Jai-GAY** [code-troopers/android-betterpickers#342]
i got the following nullPointer Exception with compile 'com.code-troopers.betterpickers:library:2.5.6'.
hopefully it does not appear in 3.x.

Portrait mode i did NOT encounter it before, today i need to prepare my app for **landscape** mode as well and discovered this issue. Has anyone having same issue on landscape mode with 3.x / 2.5.6 ?

@Override
    public void onDateSet(CalendarDatePickerDialogFragment dialog, int year, int monthOfYear,
        int dayOfMonth)
{
    Log.d(TAG, "onDateSet g_cal = " +cal.toString());
    Log.d(TAG, "RadialTimePickerDialogFragment.show b4");
    rtpd.show(getSupportFragmentManager(), FRAG_TAG_TIME_PICKER);
    Log.d(TAG, "RadialTimePickerDialogFragment.show aft");
}

12-28 14:03:15.640 9203-9203/app D/xxxxxx: onDateSet g_cal = java.util.GregorianCalendar[time=?,areFieldsSet=false,lenient=true,zone=Asia/Kuala_Lumpur,firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]
12-28 14:03:15.640 9203-9203/app D/xxxxxx: RadialTimePickerDialogFragment.show b4
12-28 14:03:15.650 9203-9203/app D/xxxxxx: RadialTimePickerDialogFragment.show aft
12-28 14:03:15.710 9203-9203/app W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4165e970)
12-28 14:03:15.730 9203-9203/app E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NullPointerException at com.codetroopers.betterpickers.radialtimepicker.RadialTimePickerDialogFragment.onCreateView(**RadialTimePickerDialogFragment.java:485**) at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290) at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677) at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536) at android.os.Handler.handleCallback(Handler.java:730) at android.os.Handler.dispatchMessage(Handler.java:92) at android.os.Looper.loop(Looper.java:158) at android.app.ActivityThread.main(ActivityThread.java:5789) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:525) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:843) at dalvik.system.NativeStart.main(Native Method)

**Comment by fchauveau** [comment]
hello @Jai-GAY 

Thx for the report.
Please tell us if it appears in 3.x.x because we will not fix on if its in 2.5.6

**Comment by Jai-GAY** [comment]
using this compile 'com.code-troopers.betterpickers:library:**3.1.0**', both orientation were OK, no application code changes on my side. just replace the 2.5.6 with 3.1.0 -> rebuild it.

Hope it helps you and appreciate for keeping the code bug free and maintaining it.
