### ISSUE TITLE
android 5.1 android.view.InflateException

### ISSUE THREAD

**Issue by Ucdemir** [code-troopers/android-betterpickers#390]
My users with 5.1 api  getting crash
```
Caused by java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
       at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:572)
       at android.view.View.<init>(View.java:3984)
       at android.widget.TextView.<init>(TextView.java:637)
       at android.widget.TextView.<init>(TextView.java:632)
       at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
       at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
       at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:892)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.codetroopers.betterpickers.radialtimepicker.RadialTimePickerDialogFragment.onCreateView(RadialTimePickerDialogFragment.java:295)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:756)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5314)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:373)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by Ucdemir** [comment]
I' am trying testing with 5.1 lolopop in my emulators there are no crash.
But my users getting crash
