### ISSUE TITLE
java.lang.NullPointerException at NumberPicker.java:579

### ISSUE THREAD

**Issue by 4bh1nav** [code-troopers/android-betterpickers#62]
I can't reproduce the bug.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxx/com.xxxx.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
       at android.app.ActivityThread.access$600(ActivityThread.java:140)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4898)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at android.os.Parcel.readIntArray(Parcel.java:784)
       at com.doomonafireball.betterpickers.numberpicker.NumberPicker$SavedState.<init>(NumberPicker.java:564)
       at com.doomonafireball.betterpickers.numberpicker.NumberPicker$SavedState.<init>(NumberPicker.java:561)
       at com.doomonafireball.betterpickers.numberpicker.a.a(NumberPicker.java:579)
       at com.doomonafireball.betterpickers.numberpicker.a.createFromParcel(NumberPicker.java:1)
       at android.os.Parcel.readParcelable(Parcel.java:2103)
       at android.os.Parcel.readValue(Parcel.java:1965)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
       at android.os.Parcel.readSparseArray(Parcel.java:1687)
       at android.os.Parcel.readValue(Parcel.java:2022)
       at android.os.Parcel.readMapInternal(Parcel.java:2226)
       at android.os.Bundle.unparcel(Bundle.java:223)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:1232)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:861)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1879)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:1490)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:893)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1879)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:215)
       at com.yyyyy.MainActivity.onCreate(MainActivity.java:79)
       at android.app.Activity.performCreate(Activity.java:5206)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
       at android.app.ActivityThread.access$600(ActivityThread.java:140)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4898)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by huteri** [comment]
Have similar issue, most of our users get affected by this crash. Please fix as soon as possible, or give us guide what to do.

**Comment by ironjan** [comment]
Can @huteri reproduce this bug?

But you could take a look at the class SavedState in https://github.com/derekbrameyer/android-betterpickers/blob/master/library/src/com/doomonafireball/betterpickers/numberpicker/NumberPicker.java - without further investigation I'm thinking that <code>mInput == null</code> is causing that issue.

**Comment by huteri** [comment]
No, I can't either @ironjan 
so is it safe to put condiitonal for that variable?

**Comment by ironjan** [comment]
i would assume it is safe to check for null and set a default value instead. 

only guesses in the following so you'll have to try this out. I did not encounter this issue nor did I investigate further than taking a quick look on the code.

mInput seems (guessing from the name) persisted user input. One use case I could imagine would be "picking a number but user wants to change that number later". Thus the picker is re-initialized with their last input. The problem could be caused by a user trying to pick a number, canceling before any input and then to try again (no input, no value for mInput, crash).

**Comment by JordanMarshall** [comment]
I have been able to reproduce the issue using BetterPickers Samples in the Play Store. I first enable 'Don't keep activities' in Developer Options to simulate the activity being stopped in the background. I then open any number picker in the app and hit the home button. The crash happens when I re-launch the app.

**Comment by huteri** [comment]
Well, it's solved, thanks @theshadowbelow for finding the way to reproduce, and @ironjan  you're right, we only need to put this before readIntArray and change the modifier of mInputSize to static, I think @derekbrameyer forgot to put this.

if (mInput == null)
mInput = new int[mInputSize];

Edit:
I found strange behaviour, it's not the best solution yet. It seems the picker creating a new instance everytime we re-launch the app.

**Comment by marcohc** [comment]
This bug is still alive :S your workaround @huteri  works, but it open the dialog twice. @derekbrameyer this bug occurs too often, any pull request with the solution?

**Comment by CedricGatay** [comment]
We will look after this one and try to fix it in the next release.

**Comment by marcohc** [comment]
@CedricGatay thank you sooooo much :)

**Comment by spectrl** [comment]
Replacing `in.readIntArray(mInput)` with `mInput = in.createIntArray()` seems to have fixed it for me.

**Comment by fchauveau** [comment]
@spectrl thx for the fix.

Can you create a PR ?

**Comment by fchauveau** [comment]
fix merged, will be released soon
