### ISSUE TITLE
NullPointerException when using NumberPickerDialogFragment [version 1.5.2]

### ISSUE THREAD

**Issue by lukcz** [code-troopers/android-betterpickers#63]
As in the title - while using NumberPickerDialogFragment i get NPE. I debuged it and it seems that after inflating view (in onCreateView method) mSet and mCancel fields  (R.id.set_button nad R.id.cancel_button) are null. Quite strange...
I get NPE when invoking mCancel.setOnClickListener.

Please see below stacktrace:
java.lang.NullPointerException
            at com.doomonafireball.betterpickers.numberpicker.NumberPickerDialogFragment.onCreateView(NumberPickerDialogFragment.java:146)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:4787)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by lukcz** [comment]
Seems like I had enviroment issues - I cannot it reproduce now, can be closed.

**Comment by 0xdRZ** [comment]
I am also getting the same issue. What is the workaround for that
