### ISSUE TITLE
Nullpointer when styling dialog

### ISSUE THREAD

**Issue by loeschg** [code-troopers/android-betterpickers#64]
I get the following stacktrace when trying to custom style my dialog:

```
java.lang.NullPointerException
        at android.widget.TextView.setTextColor(TextView.java:2641)
        at com.doomonafireball.betterpickers.datepicker.DateView.restyleViews(DateView.java:74)
        at com.doomonafireball.betterpickers.datepicker.DateView.setTheme(DateView.java:69)
        at com.doomonafireball.betterpickers.datepicker.DatePicker.restyleViews(DatePicker.java:189)
        at com.doomonafireball.betterpickers.datepicker.DatePicker.setTheme(DatePicker.java:140)
        at com.doomonafireball.betterpickers.datepicker.DatePickerDialogFragment.onCreateView(DatePickerDialogFragment.java:170)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

I have the following code snippet creating a DatePicker

```
DatePickerBuilder dpb = new DatePickerBuilder()
            .setFragmentManager(getSupportFragmentManager())
            .addDatePickerDialogHandler(new DatePickerDialogFragment.DatePickerDialogHandler() {
                @Override
                public void onDialogDateSet(int reference, int year, int monthOfYear, int dayOfMonth) {
                    // Do stuff
                }
            })
            .setStyleResId(R.style.CustomBetterPickerTheme);
    dpb.show();
```

The following is the style:

```
<style name="CustomBetterPickerTheme">
    <item name="bpTextColor">@color/my_orange</item>
</style>
```

**Comment by loeschg** [comment]
Looks like a bpTitleColor is also required

```
<style name="CustomBetterPickerTheme">
    <item name="bpTitleColor">@color/my_orange</item>
    <item name="bpTextColor">@color/my_orange</item>
</style>
```

See https://github.com/derekbrameyer/android-betterpickers/blob/master/library/src/com/doomonafireball/betterpickers/datepicker/DateView.java?source=c#L66
