### ISSUE TITLE
Added project as library and resources cant be found!

### ISSUE THREAD

**Issue by thiagolocatelli** [code-troopers/android-betterpickers#72]
Hi,

I am trying to use the library but I am always getting this error:

``` JAVA
04-09 23:32:53.433: E/AndroidRuntime(29162): FATAL EXCEPTION: main
04-09 23:32:53.433: E/AndroidRuntime(29162): android.content.res.Resources$NotFoundException: Resource ID #0x7f050029
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.content.res.Resources.getValue(Resources.java:1013)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.content.res.Resources.getColorStateList(Resources.java:774)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at com.doomonafireball.betterpickers.datepicker.DatePickerDialogFragment.onCreate(DatePickerDialogFragment.java:103)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.support.v4.app.Fragment.performCreate(Fragment.java:1477)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:893)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.os.Handler.handleCallback(Handler.java:615)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.os.Handler.dispatchMessage(Handler.java:92)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.os.Looper.loop(Looper.java:137)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at android.app.ActivityThread.main(ActivityThread.java:4745)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at java.lang.reflect.Method.invokeNative(Native Method)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at java.lang.reflect.Method.invoke(Method.java:511)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
04-09 23:32:53.433: E/AndroidRuntime(29162):    at dalvik.system.NativeStart.main(Native Method)
```

which points to

``` JAVA
       // Init defaults
        mTextColor = getResources().getColorStateList(R.color.dialog_text_color_holo_dark);
        mButtonBackgroundResId = R.drawable.button_background_dark;
        mDividerColor = getResources().getColor(R.color.default_divider_color_dark);
        mDialogBackgroundResId = R.drawable.dialog_full_holo_dark;
```

**Comment by CedricGatay** [comment]
Any news about this ?
