### ISSUE TITLE
java.lang.SecurityException: Requires VIBRATE permission

### ISSUE THREAD

**Issue by ghost** [code-troopers/android-betterpickers#91]
Hi to all,

This error is associated with the use of the CalendarDatePickerDialog and RadialTimePickerDialog views. When the "show" method is called, the captioned exception is received. I'm developing for API level 14+. When I've google'd this error, the general solution seems to be updating the below to the "AndroidManifest.xml":

<uses-permission android:name="android.permission.VIBRATE" />

This actually doesn't resolve the issue, and a point to note here, is that "uses-permission" is apparently not a recognized node, as no suggestion was received for it in Android Studio.
# Please help... The full exception string is below:

06-01 12:24:22.128    1206-1206/com.electom.reminderplus E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.electom.reminderplus, PID: 1206
    java.lang.SecurityException: Requires VIBRATE permission
            at android.os.Parcel.readException(Parcel.java:1465)
            at android.os.Parcel.readException(Parcel.java:1419)
            at android.os.IVibratorService$Stub$Proxy.vibrate(IVibratorService.java:141)
            at android.os.SystemVibrator.vibrate(SystemVibrator.java:80)
            at android.os.SystemVibrator.vibrate(SystemVibrator.java:62)
            at com.doomonafireball.betterpickers.radialtimepicker.RadialPickerLayout.tryVibrate(RadialPickerLayout.java:722)
            at com.doomonafireball.betterpickers.radialtimepicker.RadialPickerLayout.onTouch(RadialPickerLayout.java:599)
            at android.view.View.dispatchTouchEvent(View.java:7708)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2329)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1568)
            at android.app.Dialog.dispatchTouchEvent(Dialog.java:746)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2277)
            at android.view.View.dispatchPointerEvent(View.java:7893)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:138)
            at android.os.Looper.loop(Looper.java:123)
            at android.app.ActivityThread.main(ActivityThread.java:5149)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by T0bbes** [comment]
Show your AndroidManifest.xml.
Did you have include the following argument in your manifest file?

``` xml
    <uses-permission android:name="android.permission.VIBRATE"/>
```

**Comment by ghost** [comment]
Hi,

Yes, I do have that node included. Please see my file below:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.electom.aplus" >

```
<application
    android:allowBackup="true"
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/ActionBarTheme1" >
    <activity
        android:name="com.electom.reminderplus.MainActivity"
        android:label="@string/app_name" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
    <activity
        android:name="com.electom.reminderplus.activities.NewTaskActivity"
        android:parentActivityName=".MainActivity"
        android:label="@string/title_activity_new_task" >
    </activity>
    <uses-permission android:name="android.permission.VIBRATE" />
</application>
```

</manifest>

**Comment by dbaelz** [comment]
You have to move the permission outside of the `<application>` tag.

**Comment by ghost** [comment]
Thanks dbaelz!

That fixes the issue. Much appreciated!

**Comment by robertramirez** [comment]
<uses-permission android:name="android.permission.VIBRATE" /> en AndroidManifest.xml

**Comment by adjanybekov** [comment]
Why does it have to be outside?
