### ISSUE TITLE
java.lang.NoSuchMethodError: android.view.ViewGroup.requestSendAccessibilityEvent

### ISSUE THREAD

**Issue by dirkam** [code-troopers/android-betterpickers#92]
Any ideas how to fix this?

java.lang.NoSuchMethodError: android.view.ViewGroup.requestSendAccessibilityEvent
       at com.doomonafireball.betterpickers.TouchExplorationHelper.sendEventForItem(TouchExplorationHelper.java:130)
       at com.doomonafireball.betterpickers.calendardatepicker.SimpleMonthView.onDayClick(SimpleMonthView.java:506)
       at com.doomonafireball.betterpickers.calendardatepicker.SimpleMonthView.onTouchEvent(SimpleMonthView.java:252)
       at android.view.View.dispatchTouchEvent(View.java:3938)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1746)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1152)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:642)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1730)
       at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2259)
       at android.view.ViewRoot.handleMessage(ViewRoot.java:1930)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3691)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by dirkam** [comment]
Crash on 2.3.x device (can't reproduce it)

**Comment by ctanok** [comment]
Hi guys. This library was crashed in Android 2.3.3.
Device: Samsung GT-S5660 Android: 2.3.3 API: 10

public boolean requestSendAccessibilityEvent (View child, AccessibilityEvent event)
Added in API level 14
===============================Crash log=====================================

android.view.ViewGroup.requestSendAccessibilityEvent
    java.lang.NoSuchMethodError: android.view.ViewGroup.requestSendAccessibilityEvent
            at com.doomonafireball.betterpickers.TouchExplorationHelper.sendEventForItem(TouchExplorationHelper.java:130)
            at com.doomonafireball.betterpickers.calendardatepicker.SimpleMonthView.onDayClick(SimpleMonthView.java:506)
            at com.doomonafireball.betterpickers.calendardatepicker.SimpleMonthView.onTouchEvent(SimpleMonthView.java:252)
            at android.view.View.dispatchTouchEvent(View.java:3885)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1750)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1135)
            at android.app.Dialog.dispatchTouchEvent(Dialog.java:642)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1734)
            at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2216)
            at android.view.ViewRoot.handleMessage(ViewRoot.java:1887)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:123)
            at android.app.ActivityThread.main(ActivityThread.java:3687)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
            at dalvik.system.NativeStart.main(Native Method)
